version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: freelance-website-app
        restart: always
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: base64:P+7Pp/AUmr00WtmTHHUnTF5y6jzGiogqjpRS/WO4Nsk=
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root

    mysql:
        image: mariadb:10.8.3
        container_name: freelance-website-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - 3306:3306

    adminer:
        image: adminer
        container_name: freelance-website-adminer
        restart: always
        ports:
            - 8080:8080

  backend:
    image: backend   # استبدلها باسم الصورة الخاصة بك إذا كانت تختلف
    container_name: freelance-website-backend
    build:
      context: .  # المسار للمشروع إذا كنت تستخدم Dockerfile
    ports:
      - 8000:80    # ربط المنفذ 80 في الحاوية مع المنفذ 8000
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: freelance-website
      DB_USERNAME: root
      DB_PASSWORD: root
